stages:
  - deploy

deploy:
  script:
    - docker-compose up -d --force-recreate
  only:
    - main
  stage: deploy
  tags:
    - prodam_150

deploy-cron:
  script:
    - cp cron-files/sapej-cron.sh /etc/cron.daily/sapej-cron
    - chmod u+x /etc/cron.daily/sapej-cron
  when: manual
  stage: deploy
  tags:
    - prodam_150
  