stages:
  - deploy

deploy:
  script:
    - docker-compose up -d --force-recreate
  only:
    - main
  stage: deploy
  tags:
    - prodam_150

deploy-cron:
  script:
    - cp cron-files
    - /etc/cron/ chmod u+x
  when: manual
  stage: deploy
  tags:
    - prodam_150
  