version: '3.3'
services:
  juridico-dev:
    image: node:16-alpine
    container_name: juridico_dev
    restart: always
    working_dir: /app
    command: sh -c 'npm install && npm run generate && npm run development'
    environment:
      - PORT=3302
      - DATABASE_URL=mysql://root:1312Dashs@2020@192.168.107.55:3306/juridico-db
      - ELASTIC_USERNAME=sapej_siged
      - ELASTIC_PASS=oKr11Nq70ntTH6x7A9CEbDv3ZW
      - SSO_URL=https://sistemas.saude.am.gov.br/ses-sso/api/v1
      - JWT_KEY=*uDx^m9x8tbPdxU
      - SSO_SYSTEM=SAPEJ
      - SSO_TOKEN_SYSTEM=d220705f-c3ff-4640-bfd5-4c85e0c65e26
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=edVxx!JEx3beqYo*uvrr
      - ELASTIC_HOST=https://192.168.107.23:9200/
      - CRON_TOKEN=Bearer fissL805qU@
    volumes:
      - '.:/app'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - '3302:3302'
    network_mode: bridge
    
  ticados-mongodb:
      image: mongo:4.4.6
      container_name: ticados-mongodb
      restart: always
      ports:
        - "27018:27017"
      volumes:
        - mongo_data:/data/db
        - '/etc/timezone:/etc/timezone'
        - '/etc/localtime:/etc/localtime'
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: e[&W*UcGSVBruETSTW  
      network_mode: bridge