version: "3.7"
services:
  juridico-backend:
    image: juridico-api
    container_name: juridico_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - PORT=3700
    ports:
      - "3700:3700"
    networks:
      - juridico_app

networks:
  juridico_app:

volumes:
  juridico_data:
