export type Processos = {
  id_processo?: number;
  num_procedimento: string;
  fk_tipoprocesso: number;
  prazo_total: number;
  dias_corridos: string;
  fk_orgaodemandante: number;
  data_processo: Date | string;
  data_recebimento: Date | string;
  hora_recebimento: string;
  data_arquivamento?: Date | string | null;
  fk_assunto: number;
  fk_classificacao: number;
  objeto: string;
  requer_siged: string;
  numero_siged: string | null;
  data_processo_siged: Date | null;
  permanencia_siged: string | null;
  caixa_atual_siged: string | null;
  tramitacao_siged: string | null;
  fk_responsavel: number | null;
  observacao: string | null;
  descricao: string;
  dia_limite_prazo?: Date | string;
  dias_percorridos?: number;
  dias_expirados?: number;
  status_prazo: number;
  sigiloso: string | null;
  fk_status: number;
  valor_multa: number | null;
};
